namespace QuestTracker;

/// <summary>
/// Quest ID lookup table generated from DDOQT quests.json
/// Maps (quest name, level) to DDOQT quest ID
/// </summary>
public static class QuestIdLookup
{
    private static readonly Dictionary<(string Name, int Level), string> _questIds = new()
    {
        { ("The Grotto", 1), "the_grotto" },
        { ("The Storehouse's Secret", 1), "the_storehouses_secret" },
        { ("Heyton's Rest", 1), "heytons_rest" },
        { ("The Cannith Crystal", 1), "the_cannith_crystal" },
        { ("The Collaborator", 1), "the_collaborator" },
        { ("Necromancer's Doom", 1), "necromancers_doom" },
        { ("Stopping the Sahuagin", 1), "stopping_the_sahuagin" },
        { ("Sacrifices", 1), "sacrifices" },
        { ("Redemption (quest)", 1), "redemption_quest" },
        { ("Hall of the Mark", 1), "hall_of_the_mark" },
        { ("The Bugbear Bandits", 1), "the_bugbear_bandits_level_1" },
        { ("The Bugbear Bandits", 21), "the_bugbear_bandits_level_21" },
        { ("Treasure Hunt", 1), "treasure_hunt_level_1" },
        { ("Treasure Hunt", 21), "treasure_hunt_level_21" },
        { ("Caged Beast", 1), "caged_beast_level_1" },
        { ("Caged Beast", 21), "caged_beast_level_21" },
        { ("Obstructing the Orcs", 1), "obstructing_the_orcs_level_1" },
        { ("Obstructing the Orcs", 21), "obstructing_the_orcs_level_21" },
        { ("The Hobgoblin Horde", 1), "the_hobgoblin_horde_level_1" },
        { ("The Hobgoblin Horde", 21), "the_hobgoblin_horde_level_21" },
        { ("Violent Delights", 1), "violent_delights_level_1" },
        { ("Violent Delights", 21), "violent_delights_level_21" },
        { ("Watch Your Step", 1), "watch_your_step_level_1" },
        { ("Watch Your Step", 21), "watch_your_step_level_21" },
        { ("Durk's Got A Secret", 2), "durks_got_a_secret" },
        { ("Walk the Butcher's Path", 2), "walk_the_butchers_path" },
        { ("The Smuggler's Warehouse", 2), "the_smugglers_warehouse" },
        { ("Protect Baudry's Interests", 2), "protect_baudrys_interests" },
        { ("Information is Key", 2), "information_is_key" },
        { ("Stop Hazadill's Shipment", 2), "stop_hazadills_shipment" },
        { ("Retrieve the Stolen Goods", 2), "retrieve_the_stolen_goods" },
        { ("Garrison's Missing Pack", 2), "garrisons_missing_pack" },
        { ("Stealthy Repossession", 2), "stealthy_repossession" },
        { ("Recovering the Lost Tome", 2), "recovering_the_lost_tome" },
        { ("Arachnophobia", 2), "arachnophobia" },
        { ("The Miller's Debt", 2), "the_millers_debt" },
        { ("Haverdasher", 2), "haverdasher" },
        { ("Misery's Peak", 2), "miserys_peak" },
        { ("Bringing the Light", 2), "bringing_the_light" },
        { ("The Kobolds' New Ringleader", 2), "the_kobolds_new_ringleader" },
        { ("Total Chaos", 2), "total_chaos_level_2" },
        { ("Total Chaos", 22), "total_chaos_level_22" },
        { ("Redfang the Unruled", 3), "redfang_the_unruled" },
        { ("The Swiped Signet", 3), "the_swiped_signet" },
        { ("Kobold Assault", 3), "kobold_assault" },
        { ("Home Sweet Sewer", 3), "home_sweet_sewer" },
        { ("The Captives", 3), "the_captives" },
        { ("Where There's Smoke...", 3), "where_theres_smoke" },
        { ("The Kobold's Den: Clan Gnashtooth", 3), "the_kobolds_den_clan_gnashtooth" },
        { ("The Kobold's Den: Rescuing Arlos", 3), "the_kobolds_den_rescuing_arlos" },
        { ("The Sunken Sewer", 3), "the_sunken_sewer" },
        { ("Missing in Action", 3), "missing_in_action" },
        { ("Back to Basics", 3), "back_to_basics_level_3" },
        { ("Back to Basics", 32), "back_to_basics_level_32" },
        { ("The Haunting of Saltmarsh", 3), "the_haunting_of_saltmarsh_level_3" },
        { ("The Haunting of Saltmarsh", 32), "the_haunting_of_saltmarsh_level_32" },
        { ("Under the Cover of Darkness", 3), "under_the_cover_of_darkness_level_3" },
        { ("Under the Cover of Darkness", 32), "under_the_cover_of_darkness_level_32" },
        { ("What Sleeps Below", 3), "what_sleeps_below_level_3" },
        { ("What Sleeps Below", 32), "what_sleeps_below_level_32" },
        { ("Down You Go", 3), "down_you_go_level_3" },
        { ("Down You Go", 32), "down_you_go_level_32" },
        { ("Danger at Dunwater", 3), "danger_at_dunwater_level_3" },
        { ("Danger at Dunwater", 32), "danger_at_dunwater_level_32" },
        { ("The Final Enemy", 3), "the_final_enemy_level_3" },
        { ("The Final Enemy", 32), "the_final_enemy_level_32" },
        { ("Swim at Your Own Risk", 3), "swim_at_your_own_risk_level_3" },
        { ("Swim at Your Own Risk", 32), "swim_at_your_own_risk_level_32" },
        { ("The Hijacked Haul", 3), "the_hijacked_haul_level_3" },
        { ("The Hijacked Haul", 32), "the_hijacked_haul_level_32" },
        { ("Rest for the Night", 3), "rest_for_the_night_level_3" },
        { ("Rest for the Night", 32), "rest_for_the_night_level_32" },
        { ("First Strike", 3), "first_strike" },
        { ("The Hobgoblins' Captives", 3), "the_hobgoblins_captives" },
        { ("Sleeping with the Fishes", 3), "sleeping_with_the_fishes_level_3" },
        { ("Sleeping with the Fishes", 35), "sleeping_with_the_fishes_level_35" },
        { ("Endgame: Marguerite", 3), "endgame_marguerite_level_3" },
        { ("Endgame: Marguerite", 23), "endgame_marguerite_level_23" },
        { ("Setting the Wards: The Patriarchs' Crypt", 3), "setting_the_wards_the_patriarchs_crypt_level_3" },
        { ("Setting the Wards: The Patriarchs' Crypt", 23), "setting_the_wards_the_patriarchs_crypt_level_23" },
        { ("The Friar's Niece", 3), "the_friars_niece_level_3" },
        { ("The Friar's Niece", 23), "the_friars_niece_level_23" },
        { ("The Old Archives", 3), "the_old_archives_level_3" },
        { ("The Old Archives", 23), "the_old_archives_level_23" },
        { ("To Find a Witness: Archbishop Dryden", 3), "to_find_a_witness_archbishop_dryden" },
        { ("The Crypt of Gerard Dryden", 3), "the_crypt_of_gerard_dryden_level_3" },
        { ("The Crypt of Gerard Dryden", 23), "the_crypt_of_gerard_dryden_level_23" },
        { ("Return to the Sanctuary", 3), "return_to_the_sanctuary_level_3" },
        { ("Return to the Sanctuary", 23), "return_to_the_sanctuary_level_23" },
        { ("Setting the Wards: The Lower Cathedral", 3), "setting_the_wards_the_lower_cathedral_level_3" },
        { ("Setting the Wards: The Lower Cathedral", 23), "setting_the_wards_the_lower_cathedral_level_23" },
        { ("The Home of Memory", 3), "the_home_of_memory_level_3" },
        { ("The Home of Memory", 32), "the_home_of_memory_level_32" },
        { ("Heart of the Problem", 3), "heart_of_the_problem_level_3" },
        { ("Heart of the Problem", 32), "heart_of_the_problem_level_32" },
        { ("The Sacred Bounty", 3), "the_sacred_bounty_level_3" },
        { ("The Sacred Bounty", 32), "the_sacred_bounty_level_32" },
        { ("Housekeeping", 3), "housekeeping_level_3" },
        { ("Housekeeping", 32), "housekeeping_level_32" },
        { ("Rosemary's Ballad", 3), "rosemarys_ballad_level_3" },
        { ("Rosemary's Ballad", 32), "rosemarys_ballad_level_32" },
        { ("The Cloven-jaw Scourge: Blockade", 3), "the_clovenjaw_scourge_blockade" },
        { ("The Sacred Helm", 3), "the_sacred_helm" },
        { ("Irestone Inlet", 4), "irestone_inlet" },
        { ("The Depths of Darkness", 4), "the_depths_of_darkness" },
        { ("The Depths of Despair", 4), "the_depths_of_despair" },
        { ("Proof is in the Poison", 4), "proof_is_in_the_poison" },
        { ("Freshen the Air", 4), "freshen_the_air" },
        { ("Rest for the Restless", 4), "rest_for_the_restless" },
        { ("Venn's Trail: Clan Tunnelworm", 4), "venns_trail_clan_tunnelworm" },
        { ("Venn's Trail: Venn's Fate", 4), "venns_trail_venns_fate" },
        { ("Catastrophe", 4), "catastrophe_level_4" },
        { ("Catastrophe", 34), "catastrophe_level_34" },
        { ("An Explosive Situation", 4), "an_explosive_situation" },
        { ("Rats in a Cage", 4), "rats_in_a_cage_level_4" },
        { ("Rats in a Cage", 34), "rats_in_a_cage_level_34" },
        { ("The Wizard's Labyrinth", 4), "the_wizards_labyrinth_level_4" },
        { ("The Wizard's Labyrinth", 34), "the_wizards_labyrinth_level_34" },
        { ("The Knife's Edge", 4), "the_knifes_edge_level_4" },
        { ("The Knife's Edge", 34), "the_knifes_edge_level_34" },
        { ("The Darkness and the Light", 4), "the_darkness_and_the_light_level_4" },
        { ("The Darkness and the Light", 35), "the_darkness_and_the_light_level_35" },
        { ("Yarkuch's War-plans", 4), "yarkuchs_warplans" },
        { ("Whisperdoom's Spawn", 4), "whisperdooms_spawn" },
        { ("The Covered Culvert", 4), "the_covered_culvert_level_4" },
        { ("The Covered Culvert", 35), "the_covered_culvert_level_35" },
        { ("Endgame: The Archbishop's Fate", 4), "endgame_the_archbishops_fate_level_4" },
        { ("Endgame: The Archbishop's Fate", 23), "endgame_the_archbishops_fate_level_23" },
        { ("The Cloven-jaw Scourge: The Caverns of Shaagh", 4), "the_clovenjaw_scourge_the_caverns_of_shaagh" },
        { ("Stand Your Ground", 4), "stand_your_ground" },
        { ("The Bookbinder Rescue", 4), "the_bookbinder_rescue" },
        { ("The Stormreaver Fresco", 4), "the_stormreaver_fresco" },
        { ("Repossession", 4), "repossession" },
        { ("Come Out and Slay", 4), "come_out_and_slay" },
        { ("Dirty Laundry", 4), "dirty_laundry" },
        { ("The Depths of Discord", 5), "the_depths_of_discord" },
        { ("The Depths of Doom", 5), "the_depths_of_doom" },
        { ("Archer Point Defense", 5), "archer_point_defense" },
        { ("The Chamber of Insanity", 5), "the_chamber_of_insanity" },
        { ("The Lair of Summoning", 5), "the_lair_of_summoning" },
        { ("The Mystery of Delera's Tomb", 5), "the_mystery_of_deleras_tomb_level_5" },
        { ("The Mystery of Delera's Tomb", 27), "the_mystery_of_deleras_tomb_level_27" },
        { ("The Endless Revels", 5), "the_endless_revels_level_5" },
        { ("The Endless Revels", 32), "the_endless_revels_level_32" },
        { ("The Legend of the Lost Locket", 5), "the_legend_of_the_lost_locket_level_5" },
        { ("The Legend of the Lost Locket", 32), "the_legend_of_the_lost_locket_level_32" },
        { ("Make Believe", 5), "make_believe_level_5" },
        { ("Make Believe", 32), "make_believe_level_32" },
        { ("Wake Me Up Inside", 5), "wake_me_up_inside_level_5" },
        { ("Wake Me Up Inside", 32), "wake_me_up_inside_level_32" },
        { ("Combatting Corruption", 5), "combatting_corruption_level_5" },
        { ("Combatting Corruption", 32), "combatting_corruption_level_32" },
        { ("A Frosty Reception", 5), "a_frosty_reception_level_5" },
        { ("A Frosty Reception", 32), "a_frosty_reception_level_32" },
        { ("Witch Hunt", 5), "witch_hunt_level_5" },
        { ("Witch Hunt", 32), "witch_hunt_level_32" },
        { ("A Small Problem", 5), "a_small_problem_level_5" },
        { ("A Small Problem", 20), "a_small_problem_level_20" },
        { ("The Snitch", 5), "the_snitch_level_5" },
        { ("The Snitch", 20), "the_snitch_level_20" },
        { ("Under the Big Top", 5), "under_the_big_top_level_5" },
        { ("Under the Big Top", 20), "under_the_big_top_level_20" },
        { ("Partycrashers", 5), "partycrashers_level_5" },
        { ("Partycrashers", 20), "partycrashers_level_20" },
        { ("The Deadly Package: The Stronghold Key", 5), "the_deadly_package_the_stronghold_key" },
        { ("The Deadly Package: Agent of the Darguul", 5), "the_deadly_package_agent_of_the_darguul" },
        { ("Toil and Trouble", 5), "toil_and_trouble_level_5" },
        { ("Toil and Trouble", 28), "toil_and_trouble_level_28" },
        { ("Tomb of the Crimson Heart", 5), "tomb_of_the_crimson_heart" },
        { ("Tomb of the Sanguine Heart", 5), "tomb_of_the_sanguine_heart" },
        { ("Tomb of the Burning Heart", 5), "tomb_of_the_burning_heart" },
        { ("Tomb of the Immortal Heart", 5), "tomb_of_the_immortal_heart" },
        { ("Halls of Shan-To-Kor", 5), "halls_of_shantokor" },
        { ("Guard Duty", 5), "guard_duty" },
        { ("Brood of Flame", 5), "brood_of_flame" },
        { ("The Legend of Two-Toed Tobias", 5), "the_legend_of_twotoed_tobias" },
        { ("Prove Your Worth", 5), "prove_your_worth" },
        { ("Ghost of a Chance", 5), "ghost_of_a_chance" },
        { ("The Stones Run Red", 5), "the_stones_run_red" },
        { ("Gladewatch Outpost Defense", 6), "gladewatch_outpost_defense" },
        { ("The Bounty Hunter", 6), "the_bounty_hunter" },
        { ("Mirra's Sleepless Nights", 6), "mirras_sleepless_nights" },
        { ("The Forgotten Caverns", 6), "the_forgotten_caverns" },
        { ("Caged Trolls", 6), "caged_trolls" },
        { ("Purge the Heretics", 6), "purge_the_heretics" },
        { ("Redwillow's Ruins", 6), "redwillows_ruins" },
        { ("Dead Predators", 6), "dead_predators" },
        { ("The Promise of Fire", 6), "the_promise_of_fire_level_6" },
        { ("The Promise of Fire", 27), "the_promise_of_fire_level_27" },
        { ("Dread Sea Scrolls", 6), "dread_sea_scrolls_level_6" },
        { ("Dread Sea Scrolls", 32), "dread_sea_scrolls_level_32" },
        { ("Ruined Halls", 6), "ruined_halls" },
        { ("Valak's Mausoleum", 6), "valaks_mausoleum" },
        { ("Return to Delera's Tomb (quest)", 6), "return_to_deleras_tomb_quest_level_6" },
        { ("Return to Delera's Tomb (quest)", 27), "return_to_deleras_tomb_quest_level_27" },
        { ("The Chronoscope", 6), "the_chronoscope_level_6" },
        { ("The Chronoscope", 21), "the_chronoscope_level_21" },
        { ("Devil Assault (quest)", 6), "devil_assault_quest_level_6" },
        { ("Devil Assault (quest)", 21), "devil_assault_quest_level_21" },
        { ("Quid Pro Quo", 6), "quid_pro_quo_level_6" },
        { ("Quid Pro Quo", 32), "quid_pro_quo_level_32" },
        { ("Needle in a Fey Stack", 6), "needle_in_a_fey_stack_level_6" },
        { ("Needle in a Fey Stack", 32), "needle_in_a_fey_stack_level_32" },
        { ("The Knight Who Cried Windmill", 6), "the_knight_who_cried_windmill_level_6" },
        { ("The Knight Who Cried Windmill", 32), "the_knight_who_cried_windmill_level_32" },
        { ("The Thornwright", 6), "the_thornwright_level_6" },
        { ("The Thornwright", 32), "the_thornwright_level_32" },
        { ("Immortality Lessons", 6), "immortality_lessons_level_6" },
        { ("Immortality Lessons", 32), "immortality_lessons_level_32" },
        { ("The Icemount Curse", 6), "the_icemount_curse_level_6" },
        { ("The Icemount Curse", 32), "the_icemount_curse_level_32" },
        { ("The Iron Mines: Freeing Achka", 6), "the_iron_mines_freeing_achka" },
        { ("The Iron Mines: Justice for Grust", 6), "the_iron_mines_justice_for_grust" },
        { ("Doom of the Witch-doctor: The Way to Zulkash", 6), "doom_of_the_witchdoctor_the_way_to_zulkash" },
        { ("Doom of the Witch-doctor: Zulkash, Herald of Woe", 6), "doom_of_the_witchdoctor_zulkash_herald_of_woe" },
        { ("The Bloody Crypt", 6), "the_bloody_crypt" },
        { ("The Troglodytes' Get", 6), "the_troglodytes_get" },
        { ("Another Man's Treasure", 6), "another_mans_treasure_level_6" },
        { ("Another Man's Treasure", 21), "another_mans_treasure_level_21" },
        { ("Kind of a Big Deal", 6), "kind_of_a_big_deal_level_6" },
        { ("Kind of a Big Deal", 21), "kind_of_a_big_deal_level_21" },
        { ("The Price of Freedom", 6), "the_price_of_freedom_level_6" },
        { ("The Price of Freedom", 25), "the_price_of_freedom_level_25" },
        { ("Memory Lapse", 6), "memory_lapse_level_6" },
        { ("Memory Lapse", 23), "memory_lapse_level_23" },
        { ("The Tear of Dhakaan", 7), "the_tear_of_dhakaan" },
        { ("The Graverobber", 7), "the_graverobber" },
        { ("The Pit", 7), "the_pit" },
        { ("Taming the Flames", 7), "taming_the_flames" },
        { ("Gwylan's Stand", 7), "gwylans_stand" },
        { ("The Missing Party", 7), "the_missing_party_level_7" },
        { ("The Missing Party", 27), "the_missing_party_level_27" },
        { ("Free Delera", 7), "free_delera_level_7" },
        { ("Free Delera", 27), "free_delera_level_27" },
        { ("One Dame Thing After Another", 7), "one_dame_thing_after_another_level_7" },
        { ("One Dame Thing After Another", 32), "one_dame_thing_after_another_level_32" },
        { ("Through the Tulgey Wood", 7), "through_the_tulgey_wood_level_7" },
        { ("Through the Tulgey Wood", 32), "through_the_tulgey_wood_level_32" },
        { ("Storm the Beaches", 7), "storm_the_beaches_level_7" },
        { ("Storm the Beaches", 20), "storm_the_beaches_level_20" },
        { ("Bargain of Blood", 7), "bargain_of_blood_level_7" },
        { ("Bargain of Blood", 20), "bargain_of_blood_level_20" },
        { ("The Tide Turns", 7), "the_tide_turns_level_7" },
        { ("The Tide Turns", 20), "the_tide_turns_level_20" },
        { ("The Black Loch", 7), "the_black_loch_level_7" },
        { ("The Black Loch", 20), "the_black_loch_level_20" },
        { ("The Grey Moon's Den: Extermination", 7), "the_grey_moons_den_extermination" },
        { ("The Grey Moon's Den: The Trollish Scourge", 7), "the_grey_moons_den_the_trollish_scourge" },
        { ("The Last Move: The Way to Yarkuch", 7), "the_last_move_the_way_to_yarkuch" },
        { ("The Last Move: Yarkuch's Last Stand", 7), "the_last_move_yarkuchs_last_stand" },
        { ("Captive of the Hidden God", 7), "captive_of_the_hidden_god_level_7" },
        { ("Captive of the Hidden God", 33), "captive_of_the_hidden_god_level_33" },
        { ("The Curse and the Captive Crustacean", 7), "the_curse_and_the_captive_crustacean_level_7" },
        { ("The Curse and the Captive Crustacean", 33), "the_curse_and_the_captive_crustacean_level_33" },
        { ("Bullywugs and Booby Traps", 7), "bullywugs_and_booby_traps_level_7" },
        { ("Bullywugs and Booby Traps", 33), "bullywugs_and_booby_traps_level_33" },
        { ("Plundering Pirates' Point", 7), "plundering_pirates_point_level_7" },
        { ("Plundering Pirates' Point", 33), "plundering_pirates_point_level_33" },
        { ("Spiders and Flies", 7), "spiders_and_flies_level_7" },
        { ("Spiders and Flies", 33), "spiders_and_flies_level_33" },
        { ("The Stone Crypt Chronicle", 7), "the_stone_crypt_chronicle_level_7" },
        { ("The Stone Crypt Chronicle", 33), "the_stone_crypt_chronicle_level_33" },
        { ("The Trouble with Tar Pits", 7), "the_trouble_with_tar_pits_level_7" },
        { ("The Trouble with Tar Pits", 33), "the_trouble_with_tar_pits_level_33" },
        { ("Trials of the Triceratops", 7), "trials_of_the_triceratops_level_7" },
        { ("Trials of the Triceratops", 33), "trials_of_the_triceratops_level_33" },
        { ("Whispers of Return", 7), "whispers_of_return_level_7" },
        { ("Whispers of Return", 33), "whispers_of_return_level_33" },
        { ("Wild Thing", 7), "wild_thing_level_7" },
        { ("Wild Thing", 33), "wild_thing_level_33" },
        { ("All Hail the King", 7), "all_hail_the_king_level_7" },
        { ("All Hail the King", 33), "all_hail_the_king_level_33" },
        { ("The Scoundrel's Run", 7), "the_scoundrels_run" },
        { ("Old Grey Garl", 7), "old_grey_garl" },
        { ("The Xorian Cipher", 8), "the_xorian_cipher" },
        { ("The Path to Madness", 8), "the_path_to_madness" },
        { ("Stormcleave Outpost", 8), "stormcleave_outpost" },
        { ("The Faithful Departed", 8), "the_faithful_departed" },
        { ("Haunted Library", 8), "haunted_library" },
        { ("Stromvauld's Mine", 8), "stromvaulds_mine" },
        { ("Caverns of Korromar", 8), "caverns_of_korromar" },
        { ("Slave Pits of the Undercity", 8), "slave_pits_of_the_undercity_level_8" },
        { ("Slave Pits of the Undercity", 31), "slave_pits_of_the_undercity_level_31" },
        { ("Secret of the Slavers' Stockade", 8), "secret_of_the_slavers_stockade_level_8" },
        { ("Secret of the Slavers' Stockade", 31), "secret_of_the_slavers_stockade_level_31" },
        { ("Assault on the Aerie of the Slave Lords", 8), "assault_on_the_aerie_of_the_slave_lords_level_8" },
        { ("Assault on the Aerie of the Slave Lords", 31), "assault_on_the_aerie_of_the_slave_lords_level_31" },
        { ("Thrall of the Necromancer", 8), "thrall_of_the_necromancer_level_8" },
        { ("Thrall of the Necromancer", 27), "thrall_of_the_necromancer_level_27" },
        { ("In Need of Supplies", 8), "in_need_of_supplies" },
        { ("The Rescue", 8), "the_rescue" },
        { ("Spies in the House", 8), "spies_in_the_house_level_8" },
        { ("Spies in the House", 21), "spies_in_the_house_level_21" },
        { ("The Temple Outpost: Captives of the Cult", 8), "the_temple_outpost_captives_of_the_cult" },
        { ("The Temple Outpost: The Libram of the Six", 8), "the_temple_outpost_the_libram_of_the_six" },
        { ("The Body Snatchers", 8), "the_body_snatchers_level_8" },
        { ("The Body Snatchers", 36), "the_body_snatchers_level_36" },
        { ("The Proper Authorities", 8), "the_proper_authorities_level_8" },
        { ("The Proper Authorities", 36), "the_proper_authorities_level_36" },
        { ("Ends and Means", 8), "ends_and_means_level_8" },
        { ("Ends and Means", 36), "ends_and_means_level_36" },
        { ("A Light in the Attic", 8), "a_light_in_the_attic_level_8" },
        { ("A Light in the Attic", 36), "a_light_in_the_attic_level_36" },
        { ("Cold Snap", 8), "cold_snap_level_8" },
        { ("Cold Snap", 36), "cold_snap_level_36" },
        { ("Beneath the City Streets", 8), "beneath_the_city_streets_level_8" },
        { ("Beneath the City Streets", 36), "beneath_the_city_streets_level_36" },
        { ("Locked Away (Part One)", 8), "locked_away_part_one_level_8" },
        { ("Locked Away (Part One)", 36), "locked_away_part_one_level_36" },
        { ("Snowfall and Sunlight", 8), "snowfall_and_sunlight_level_8" },
        { ("Snowfall and Sunlight", 36), "snowfall_and_sunlight_level_36" },
        { ("Locked Away (Part Two)", 8), "locked_away_part_two_level_8" },
        { ("Locked Away (Part Two)", 36), "locked_away_part_two_level_36" },
        { ("A Miner Sacrifice", 8), "a_miner_sacrifice_level_8" },
        { ("A Miner Sacrifice", 36), "a_miner_sacrifice_level_36" },
        { ("The Wish", 8), "the_wish_level_8" },
        { ("The Wish", 36), "the_wish_level_36" },
        { ("Special Delivery", 8), "special_delivery_level_8" },
        { ("Special Delivery", 36), "special_delivery_level_36" },
        { ("Zoo Creeper", 8), "zoo_creeper_level_8" },
        { ("Zoo Creeper", 36), "zoo_creeper_level_36" },
        { ("Body and Mind", 8), "body_and_mind_level_8" },
        { ("Body and Mind", 36), "body_and_mind_level_36" },
        { ("Fall of the Forbidden Temple", 8), "fall_of_the_forbidden_temple_level_8" },
        { ("Fall of the Forbidden Temple", 34), "fall_of_the_forbidden_temple_level_34" },
        { ("Tomb of the Shadow Guard", 8), "tomb_of_the_shadow_guard" },
        { ("Tomb of the Shadow King", 8), "tomb_of_the_shadow_king" },
        { ("Tomb of the Shadow Knight", 8), "tomb_of_the_shadow_knight" },
        { ("Tomb of the Shadow Lord", 8), "tomb_of_the_shadow_lord" },
        { ("ToEE: First Level and Earth Temple", 8), "toee_first_level_and_earth_temple_level_8" },
        { ("ToEE: First Level and Earth Temple", 34), "toee_first_level_and_earth_temple_level_34" },
        { ("ToEE: Water Node", 8), "toee_water_node_level_8" },
        { ("ToEE: Water Node", 34), "toee_water_node_level_34" },
        { ("ToEE: Lower Temple Complex", 8), "toee_lower_temple_complex_level_8" },
        { ("ToEE: Lower Temple Complex", 34), "toee_lower_temple_complex_level_34" },
        { ("ToEE: Fire Node", 8), "toee_fire_node_level_8" },
        { ("ToEE: Fire Node", 34), "toee_fire_node_level_34" },
        { ("ToEE: Earth Node", 8), "toee_earth_node_level_8" },
        { ("ToEE: Earth Node", 34), "toee_earth_node_level_34" },
        { ("ToEE: Depths of the Temple", 8), "toee_depths_of_the_temple_level_8" },
        { ("ToEE: Depths of the Temple", 34), "toee_depths_of_the_temple_level_34" },
        { ("ToEE: Air Node", 8), "toee_air_node_level_8" },
        { ("ToEE: Air Node", 34), "toee_air_node_level_34" },
        { ("The Prisoner", 8), "the_prisoner_level_8" },
        { ("The Prisoner", 21), "the_prisoner_level_21" },
        { ("Tharashk Arena", 8), "tharashk_arena_level_8" },
        { ("Tharashk Arena", 21), "tharashk_arena_level_21" },
        { ("The Church and the Cult", 9), "the_church_and_the_cult" },
        { ("The Keeper's Sanctuary", 9), "the_keepers_sanctuary" },
        { ("The Library of Threnal", 9), "the_library_of_threnal" },
        { ("The Giant Lieutenants", 9), "the_giant_lieutenants" },
        { ("The Giants' Lair", 9), "the_giants_lair" },
        { ("The Missing Expedition", 9), "the_missing_expedition" },
        { ("Entering the Gate Chamber", 9), "entering_the_gate_chamber" },
        { ("The Threnal Arena", 9), "the_threnal_arena" },
        { ("The Fane of the Six: Cleansing the Temple", 9), "the_fane_of_the_six_cleansing_the_temple" },
        { ("The Fane of the Six: Fall of the Prelate", 9), "the_fane_of_the_six_fall_of_the_prelate" },
        { ("The Shadow Crypt", 9), "the_shadow_crypt" },
        { ("The Claw of Vulkoor", 9), "the_claw_of_vulkoor_level_9" },
        { ("The Claw of Vulkoor", 21), "the_claw_of_vulkoor_level_21" },
        { ("Fathom the Depths", 9), "fathom_the_depths_level_9" },
        { ("Fathom the Depths", 21), "fathom_the_depths_level_21" },
        { ("Into the Deep", 9), "into_the_deep_level_9" },
        { ("Into the Deep", 21), "into_the_deep_level_21" },
        { ("The Last Stand", 9), "the_last_stand_level_9" },
        { ("The Last Stand", 21), "the_last_stand_level_21" },
        { ("Gateway to Khyber", 9), "gateway_to_khyber" },
        { ("Haywire Foundry", 9), "haywire_foundry_level_9" },
        { ("Haywire Foundry", 22), "haywire_foundry_level_22" },
        { ("The Jungle of Khyber", 9), "the_jungle_of_khyber_level_9" },
        { ("The Jungle of Khyber", 22), "the_jungle_of_khyber_level_22" },
        { ("White Plume Mountain", 9), "white_plume_mountain_level_9" },
        { ("White Plume Mountain", 32), "white_plume_mountain_level_32" },
        { ("Hiding in Plain Sight", 10), "hiding_in_plain_sight" },
        { ("Reclamation", 10), "reclamation" },
        { ("Sykros' Jewel", 10), "sykros_jewel" },
        { ("Tempest's Spine", 10), "tempests_spine" },
        { ("The Chamber of Rahmat", 10), "the_chamber_of_rahmat" },
        { ("The Newcomers", 10), "the_newcomers_level_10" },
        { ("The Newcomers", 31), "the_newcomers_level_31" },
        { ("Black and Blue", 10), "black_and_blue_level_10" },
        { ("Black and Blue", 31), "black_and_blue_level_31" },
        { ("Into the Mists", 10), "into_the_mists_level_10" },
        { ("Into the Mists", 31), "into_the_mists_level_31" },
        { ("Fresh-baked Dreams", 10), "freshbaked_dreams_level_10" },
        { ("Fresh-baked Dreams", 31), "freshbaked_dreams_level_31" },
        { ("Death House", 10), "death_house_level_10" },
        { ("Death House", 31), "death_house_level_31" },
        { ("An Invitation to Dinner", 10), "an_invitation_to_dinner_level_10" },
        { ("An Invitation to Dinner", 32), "an_invitation_to_dinner_level_32" },
        { ("The Giants' Supplies", 10), "the_giants_supplies" },
        { ("Secure the Area", 10), "secure_the_area" },
        { ("Hold for Reinforcements", 10), "hold_for_reinforcements" },
        { ("The Gate Chamber", 10), "the_gate_chamber" },
        { ("Escort the Expedition", 10), "escort_the_expedition" },
        { ("The Sanctum: Quench the Flames", 10), "the_sanctum_quench_the_flames" },
        { ("The Sanctum: Church of the Fury", 10), "the_sanctum_church_of_the_fury" },
        { ("Slavers of the Shrieking Mines", 10), "slavers_of_the_shrieking_mines" },
        { ("Bring Me the Head of Ghola-Fan!", 10), "bring_me_the_head_of_gholafan" },
        { ("The Vault of Night", 10), "the_vault_of_night_level_10" },
        { ("The Vault of Night", 22), "the_vault_of_night_level_22" },
        { ("Plane of Night", 10), "plane_of_night_level_10" },
        { ("Plane of Night", 22), "plane_of_night_level_22" },
        { ("The Enemy Within", 11), "the_enemy_within" },
        { ("Dreams of Insanity", 11), "dreams_of_insanity" },
        { ("Made to Order", 11), "made_to_order" },
        { ("The Spawn of Whisperdoom", 11), "the_spawn_of_whisperdoom" },
        { ("And the Dead Shall Rise...", 11), "and_the_dead_shall_rise" },
        { ("From Beyond the Grave", 11), "from_beyond_the_grave" },
        { ("Desert Caravan", 11), "desert_caravan" },
        { ("Purge the Fallen Shrine", 11), "purge_the_fallen_shrine" },
        { ("The Chamber of Kourush", 11), "the_chamber_of_kourush" },
        { ("Maraud the Mines", 11), "maraud_the_mines" },
        { ("Raid the Vulkoorim", 11), "raid_the_vulkoorim" },
        { ("An Offering of Blood", 11), "an_offering_of_blood_level_11" },
        { ("An Offering of Blood", 21), "an_offering_of_blood_level_21" },
        { ("Oath of Vengeance", 11), "oath_of_vengeance_level_11" },
        { ("Oath of Vengeance", 31), "oath_of_vengeance_level_31" },
        { ("A Raven at the Door", 11), "a_raven_at_the_door_level_11" },
        { ("A Raven at the Door", 31), "a_raven_at_the_door_level_31" },
        { ("Mad Tea Party", 11), "mad_tea_party_level_11" },
        { ("Mad Tea Party", 31), "mad_tea_party_level_31" },
        { ("Sealed in Amber", 11), "sealed_in_amber_level_11" },
        { ("Sealed in Amber", 31), "sealed_in_amber_level_31" },
        { ("Tomb of the Blighted", 11), "tomb_of_the_blighted" },
        { ("Tomb of the Forbidden", 11), "tomb_of_the_forbidden" },
        { ("Tomb of the Tormented", 11), "tomb_of_the_tormented" },
        { ("Tomb of the Unhallowed", 11), "tomb_of_the_unhallowed" },
        { ("The Twilight Forge", 11), "the_twilight_forge" },
        { ("A Relic of a Sovereign Past", 12), "a_relic_of_a_sovereign_past" },
        { ("Diplomatic Impunity", 12), "diplomatic_impunity_level_12" },
        { ("Diplomatic Impunity", 34), "diplomatic_impunity_level_34" },
        { ("Eyes of Stone", 12), "eyes_of_stone_level_12" },
        { ("Eyes of Stone", 34), "eyes_of_stone_level_34" },
        { ("Frame Work", 12), "frame_work_level_12" },
        { ("Frame Work", 34), "frame_work_level_34" },
        { ("Invaders!", 12), "invaders" },
        { ("Against the Demon Queen (quest)", 12), "against_the_demon_queen_quest_level_12" },
        { ("Against the Demon Queen (quest)", 22), "against_the_demon_queen_quest_level_22" },
        { ("The Chamber of Raiyum", 12), "the_chamber_of_raiyum_level_12" },
        { ("The Chamber of Raiyum", 22), "the_chamber_of_raiyum_level_22" },
        { ("Chains of Flame", 12), "chains_of_flame_level_12" },
        { ("Chains of Flame", 22), "chains_of_flame_level_22" },
        { ("Zawabi's Revenge", 12), "zawabis_revenge_level_12" },
        { ("Zawabi's Revenge", 22), "zawabis_revenge_level_22" },
        { ("Wrath of the Earth", 12), "wrath_of_the_earth_level_12" },
        { ("Wrath of the Earth", 32), "wrath_of_the_earth_level_32" },
        { ("Sunrise", 12), "sunrise_level_12" },
        { ("Sunrise", 31), "sunrise_level_31" },
        { ("The Final Vintage", 12), "the_final_vintage_level_12" },
        { ("The Final Vintage", 31), "the_final_vintage_level_31" },
        { ("Ravens' Bane", 12), "ravens_bane_level_12" },
        { ("Ravens' Bane", 31), "ravens_bane_level_31" },
        { ("An Element of Chaos", 12), "an_element_of_chaos_level_12" },
        { ("An Element of Chaos", 32), "an_element_of_chaos_level_32" },
        { ("Eye Know Whodunnit", 12), "eye_know_whodunnit_level_12" },
        { ("Eye Know Whodunnit", 32), "eye_know_whodunnit_level_32" },
        { ("Seizing the Dawn", 12), "seizing_the_dawn_level_12" },
        { ("Seizing the Dawn", 32), "seizing_the_dawn_level_32" },
        { ("Beautiful Nightmares", 12), "beautiful_nightmares_level_12" },
        { ("Beautiful Nightmares", 32), "beautiful_nightmares_level_32" },
        { ("The Cursed Crypt", 12), "the_cursed_crypt" },
        { ("The Titan Awakes", 12), "the_titan_awakes" },
        { ("Mired in Kobolds", 13), "mired_in_kobolds" },
        { ("Dinosaur Crisis", 13), "dinosaur_crisis_level_13" },
        { ("Dinosaur Crisis", 28), "dinosaur_crisis_level_28" },
        { ("Blockade Buster", 13), "blockade_buster_level_13" },
        { ("Blockade Buster", 34), "blockade_buster_level_34" },
        { ("Undermine", 13), "undermine_level_13" },
        { ("Undermine", 34), "undermine_level_34" },
        { ("Assault on Summerfield", 13), "assault_on_summerfield_level_13" },
        { ("Assault on Summerfield", 34), "assault_on_summerfield_level_34" },
        { ("Siegebreaker", 13), "siegebreaker_level_13" },
        { ("Siegebreaker", 34), "siegebreaker_level_34" },
        { ("Ettercap Incursion", 13), "ettercap_incursion_level_13" },
        { ("Ettercap Incursion", 35), "ettercap_incursion_level_35" },
        { ("Seeds of Decay", 13), "seeds_of_decay_level_13" },
        { ("Seeds of Decay", 35), "seeds_of_decay_level_35" },
        { ("The Safehold", 13), "the_safehold_level_13" },
        { ("The Safehold", 35), "the_safehold_level_35" },
        { ("Death Hosts This Banquet", 13), "death_hosts_this_banquet_level_13" },
        { ("Death Hosts This Banquet", 35), "death_hosts_this_banquet_level_35" },
        { ("Oghma's Song", 13), "oghmas_song_level_13" },
        { ("Oghma's Song", 35), "oghmas_song_level_35" },
        { ("Secrets of the Red Wizards", 13), "secrets_of_the_red_wizards_level_13" },
        { ("Secrets of the Red Wizards", 35), "secrets_of_the_red_wizards_level_35" },
        { ("Portal to Below", 13), "portal_to_below_level_13" },
        { ("Portal to Below", 35), "portal_to_below_level_35" },
        { ("Book Burning", 13), "book_burning_level_13" },
        { ("Book Burning", 35), "book_burning_level_35" },
        { ("Times Long Past", 13), "times_long_past_level_13" },
        { ("Times Long Past", 35), "times_long_past_level_35" },
        { ("The Key to the Mythal", 13), "the_key_to_the_mythal_level_13" },
        { ("The Key to the Mythal", 35), "the_key_to_the_mythal_level_35" },
        { ("The Zulkir's Plan", 13), "the_zulkirs_plan_level_13" },
        { ("The Zulkir's Plan", 35), "the_zulkirs_plan_level_35" },
        { ("Voices of the Dead", 13), "voices_of_the_dead_level_13" },
        { ("Voices of the Dead", 35), "voices_of_the_dead_level_35" },
        { ("The House of Gems", 13), "the_house_of_gems_level_13" },
        { ("The House of Gems", 35), "the_house_of_gems_level_35" },
        { ("A Cry for Help", 13), "a_cry_for_help_level_13" },
        { ("A Cry for Help", 24), "a_cry_for_help_level_24" },
        { ("Feast or Famine", 13), "feast_or_famine_level_13" },
        { ("Feast or Famine", 24), "feast_or_famine_level_24" },
        { ("Foundation of Discord", 13), "foundation_of_discord_level_13" },
        { ("Foundation of Discord", 24), "foundation_of_discord_level_24" },
        { ("The Maze of Madness", 13), "the_maze_of_madness_level_13" },
        { ("The Maze of Madness", 24), "the_maze_of_madness_level_24" },
        { ("Trial by Fire", 13), "trial_by_fire_level_13" },
        { ("Trial by Fire", 24), "trial_by_fire_level_24" },
        { ("The Archons' Trial", 13), "the_archons_trial_level_13" },
        { ("The Archons' Trial", 30), "the_archons_trial_level_30" },
        { ("Demon Assault", 13), "demon_assault_level_13" },
        { ("Demon Assault", 30), "demon_assault_level_30" },
        { ("The Devil's Details", 13), "the_devils_details_level_13" },
        { ("The Devil's Details", 30), "the_devils_details_level_30" },
        { ("Tower of Frost", 14), "tower_of_frost_level_14" },
        { ("Tower of Frost", 28), "tower_of_frost_level_28" },
        { ("Night Falls on Stormreach", 14), "night_falls_on_stormreach_level_14" },
        { ("Night Falls on Stormreach", 31), "night_falls_on_stormreach_level_31" },
        { ("Quarantine", 14), "quarantine_level_14" },
        { ("Quarantine", 31), "quarantine_level_31" },
        { ("The Madness of Crowds", 14), "the_madness_of_crowds_level_14" },
        { ("The Madness of Crowds", 31), "the_madness_of_crowds_level_31" },
        { ("Toxic Treatment", 14), "toxic_treatment_level_14" },
        { ("Toxic Treatment", 31), "toxic_treatment_level_31" },
        { ("The Age of Rage", 14), "the_age_of_rage_level_14" },
        { ("The Age of Rage", 31), "the_age_of_rage_level_31" },
        { ("The Prison of the Planes", 14), "the_prison_of_the_planes" },
        { ("The Reaver's Fate", 14), "the_reavers_fate" },
        { ("A Cabal for One", 14), "a_cabal_for_one" },
        { ("Madstone Crater", 14), "madstone_crater" },
        { ("The Crucible", 14), "the_crucible_level_14" },
        { ("The Crucible", 24), "the_crucible_level_24" },
        { ("Gianthold Tor", 14), "gianthold_tor" },
        { ("Tavern Brawl", 14), "tavern_brawl_level_14" },
        { ("Tavern Brawl", 30), "tavern_brawl_level_30" },
        { ("Grim and Barett", 14), "grim_and_barett_level_14" },
        { ("Grim and Barett", 30), "grim_and_barett_level_30" },
        { ("Subversion", 14), "subversion_level_14" },
        { ("Subversion", 30), "subversion_level_30" },
        { ("Multitude of Menace", 14), "multitude_of_menace_level_14" },
        { ("Multitude of Menace", 30), "multitude_of_menace_level_30" },
        { ("Desecrated Temple of Vol", 14), "desecrated_temple_of_vol" },
        { ("Flesh Maker's Laboratory", 14), "flesh_makers_laboratory" },
        { ("Ghosts of Perdition", 14), "ghosts_of_perdition" },
        { ("Inferno of the Damned", 14), "inferno_of_the_damned" },
        { ("Delirium", 15), "delirium" },
        { ("Acid Wit", 15), "acid_wit" },
        { ("Escape Plan", 15), "escape_plan" },
        { ("Disciples of Shar", 15), "disciples_of_shar" },
        { ("Search and Rescue", 15), "search_and_rescue_level_15" },
        { ("Search and Rescue", 31), "search_and_rescue_level_31" },
        { ("Lost at Sea", 15), "lost_at_sea_level_15" },
        { ("Lost at Sea", 32), "lost_at_sea_level_32" },
        { ("Missing", 15), "missing" },
        { ("Fear Factory", 15), "fear_factory" },
        { ("Sinister Storage", 15), "sinister_storage" },
        { ("In The Flesh", 15), "in_the_flesh" },
        { ("Just Business", 15), "just_business_level_15" },
        { ("Just Business", 32), "just_business_level_32" },
        { ("Ruinous Schemes", 15), "ruinous_schemes_level_15" },
        { ("Ruinous Schemes", 32), "ruinous_schemes_level_32" },
        { ("Smash and Burn", 15), "smash_and_burn_level_15" },
        { ("Smash and Burn", 32), "smash_and_burn_level_32" },
        { ("A Sharn Welcome", 15), "a_sharn_welcome_level_15" },
        { ("A Sharn Welcome", 32), "a_sharn_welcome_level_32" },
        { ("Best Laid Plans", 15), "best_laid_plans_level_15" },
        { ("Best Laid Plans", 32), "best_laid_plans_level_32" },
        { ("Red Rain", 15), "red_rain_level_15" },
        { ("Red Rain", 32), "red_rain_level_32" },
        { ("The Wraithcallers", 15), "the_wraithcallers_level_15" },
        { ("The Wraithcallers", 32), "the_wraithcallers_level_32" },
        { ("Thralls of the Fungus Lord", 15), "thralls_of_the_fungus_lord_level_15" },
        { ("Thralls of the Fungus Lord", 32), "thralls_of_the_fungus_lord_level_32" },
        { ("The Same Old Song", 15), "the_same_old_song_level_15" },
        { ("The Same Old Song", 32), "the_same_old_song_level_32" },
        { ("Shadow of a Doubt", 15), "shadow_of_a_doubt" },
        { ("Graveyard Shift", 15), "graveyard_shift_level_15" },
        { ("Graveyard Shift", 31), "graveyard_shift_level_31" },
        { ("Records of the Past", 15), "records_of_the_past_level_15" },
        { ("Records of the Past", 31), "records_of_the_past_level_31" },
        { ("Third Time's a Charm", 15), "third_times_a_charm_level_15" },
        { ("Third Time's a Charm", 31), "third_times_a_charm_level_31" },
        { ("Strike Back", 15), "strike_back_level_15" },
        { ("Strike Back", 31), "strike_back_level_31" },
        { ("Desire in the Dark", 15), "desire_in_the_dark_level_15" },
        { ("Desire in the Dark", 31), "desire_in_the_dark_level_31" },
        { ("Litany of the Dead", 15), "litany_of_the_dead" },
        { ("To Curse the Sky", 15), "to_curse_the_sky_level_15" },
        { ("To Curse the Sky", 31), "to_curse_the_sky_level_31" },
        { ("Creeping Death", 15), "creeping_death_level_15" },
        { ("Creeping Death", 31), "creeping_death_level_31" },
        { ("The Lords of Dust", 16), "the_lords_of_dust_level_16" },
        { ("The Lords of Dust", 21), "the_lords_of_dust_level_21" },
        { ("The Spinner of Shadows", 16), "the_spinner_of_shadows_level_16" },
        { ("The Spinner of Shadows", 21), "the_spinner_of_shadows_level_21" },
        { ("Servants of the Overlord", 16), "servants_of_the_overlord_level_16" },
        { ("Servants of the Overlord", 21), "servants_of_the_overlord_level_21" },
        { ("The Mask of Deception", 16), "the_mask_of_deception_level_16" },
        { ("The Mask of Deception", 30), "the_mask_of_deception_level_30" },
        { ("Beyond the Rift", 16), "beyond_the_rift_level_16" },
        { ("Beyond the Rift", 21), "beyond_the_rift_level_21" },
        { ("Army of Eternal Night", 16), "army_of_eternal_night_level_16" },
        { ("Army of Eternal Night", 33), "army_of_eternal_night_level_33" },
        { ("Order in the Court!", 16), "order_in_the_court_level_16" },
        { ("Order in the Court!", 33), "order_in_the_court_level_33" },
        { ("Growing Pains", 16), "growing_pains_level_16" },
        { ("Growing Pains", 33), "growing_pains_level_33" },
        { ("The Hand and the Eyes", 16), "the_hand_and_the_eyes_level_16" },
        { ("The Hand and the Eyes", 33), "the_hand_and_the_eyes_level_33" },
        { ("Three Paths to Battle", 16), "three_paths_to_battle_level_16" },
        { ("Three Paths to Battle", 33), "three_paths_to_battle_level_33" },
        { ("No Refunds", 16), "no_refunds_level_16" },
        { ("No Refunds", 32), "no_refunds_level_32" },
        { ("House of Pain", 16), "house_of_pain_level_16" },
        { ("House of Pain", 32), "house_of_pain_level_32" },
        { ("Blown Deadline", 16), "blown_deadline_level_16" },
        { ("Blown Deadline", 32), "blown_deadline_level_32" },
        { ("Reach for the Sky", 16), "reach_for_the_sky_level_16" },
        { ("Reach for the Sky", 32), "reach_for_the_sky_level_32" },
        { ("Scavenger Hunt", 16), "scavenger_hunt_level_16" },
        { ("Scavenger Hunt", 32), "scavenger_hunt_level_32" },
        { ("The Magma Must Flow", 16), "the_magma_must_flow_level_16" },
        { ("The Magma Must Flow", 32), "the_magma_must_flow_level_32" },
        { ("Security Detail", 16), "security_detail_level_16" },
        { ("Security Detail", 32), "security_detail_level_32" },
        { ("Roll Call", 16), "roll_call_level_16" },
        { ("Roll Call", 32), "roll_call_level_32" },
        { ("A Lesson in Deception", 16), "a_lesson_in_deception_level_16" },
        { ("A Lesson in Deception", 26), "a_lesson_in_deception_level_26" },
        { ("Army of Shadow", 16), "army_of_shadow_level_16" },
        { ("Army of Shadow", 26), "army_of_shadow_level_26" },
        { ("Friends in Low Places", 16), "friends_in_low_places_level_16" },
        { ("Friends in Low Places", 26), "friends_in_low_places_level_26" },
        { ("The Thrill of the Hunt", 16), "the_thrill_of_the_hunt_level_16" },
        { ("The Thrill of the Hunt", 26), "the_thrill_of_the_hunt_level_26" },
        { ("Through a Mirror Darkly", 16), "through_a_mirror_darkly_level_16" },
        { ("Through a Mirror Darkly", 26), "through_a_mirror_darkly_level_26" },
        { ("Let Sleeping Dust Lie", 16), "let_sleeping_dust_lie" },
        { ("Ritual Sacrifice", 16), "ritual_sacrifice" },
        { ("Running with the Devils", 16), "running_with_the_devils" },
        { ("Rainbow in the Dark", 16), "rainbow_in_the_dark" },
        { ("The Coalescence Chamber", 16), "the_coalescence_chamber" },
        { ("Good Intentions", 17), "good_intentions_level_17" },
        { ("Good Intentions", 31), "good_intentions_level_31" },
        { ("The Lord of Stone", 17), "the_lord_of_stone" },
        { ("Acute Delirium", 17), "acute_delirium" },
        { ("The Lord of Eyes", 17), "the_lord_of_eyes" },
        { ("The Sane Asylum", 17), "the_sane_asylum" },
        { ("Outbreak", 17), "outbreak_level_17" },
        { ("Outbreak", 23), "outbreak_level_23" },
        { ("Thorn and Paw", 17), "thorn_and_paw_level_17" },
        { ("Thorn and Paw", 23), "thorn_and_paw_level_23" },
        { ("Overgrowth", 17), "overgrowth_level_17" },
        { ("Overgrowth", 23), "overgrowth_level_23" },
        { ("The Druid's Curse", 17), "the_druids_curse_level_17" },
        { ("The Druid's Curse", 23), "the_druids_curse_level_23" },
        { ("Ascension Chamber", 17), "ascension_chamber" },
        { ("Enter the Kobold", 17), "enter_the_kobold" },
        { ("Stealer of Souls", 17), "stealer_of_souls" },
        { ("Monastery of the Scorpion", 17), "monastery_of_the_scorpion" },
        { ("Prey on the Hunter", 17), "prey_on_the_hunter" },
        { ("Safety in Numbers", 17), "safety_in_numbers_level_17" },
        { ("Safety in Numbers", 32), "safety_in_numbers_level_32" },
        { ("Finding Dorris", 17), "finding_dorris_level_17" },
        { ("Finding Dorris", 32), "finding_dorris_level_32" },
        { ("The Underlane Assignment", 17), "the_underlane_assignment_level_17" },
        { ("The Underlane Assignment", 32), "the_underlane_assignment_level_32" },
        { ("Members Only", 17), "members_only_level_17" },
        { ("Members Only", 32), "members_only_level_32" },
        { ("The Offshore Account", 17), "the_offshore_account_level_17" },
        { ("The Offshore Account", 32), "the_offshore_account_level_32" },
        { ("Soul Survivor", 17), "soul_survivor_level_17" },
        { ("Soul Survivor", 32), "soul_survivor_level_32" },
        { ("The Shroud", 17), "the_shroud" },
        { ("In the Demon's Den", 18), "in_the_demons_den" },
        { ("Kill Ten Rats", 18), "kill_ten_rats_level_18" },
        { ("Kill Ten Rats", 34), "kill_ten_rats_level_34" },
        { ("Fashion Madness", 18), "fashion_madness_level_18" },
        { ("Fashion Madness", 26), "fashion_madness_level_26" },
        { ("Terminal Delirium", 18), "terminal_delirium_level_18" },
        { ("Terminal Delirium", 26), "terminal_delirium_level_26" },
        { ("Palace of Stone", 18), "palace_of_stone_level_18" },
        { ("Palace of Stone", 26), "palace_of_stone_level_26" },
        { ("Fred's First Date", 18), "freds_first_date_level_18" },
        { ("Fred's First Date", 34), "freds_first_date_level_34" },
        { ("This Old Haunt", 18), "this_old_haunt_level_18" },
        { ("This Old Haunt", 34), "this_old_haunt_level_34" },
        { ("Too Many Cooks", 18), "too_many_cooks_level_18" },
        { ("Too Many Cooks", 34), "too_many_cooks_level_34" },
        { ("A Stay at the Inn", 18), "a_stay_at_the_inn_level_18" },
        { ("A Stay at the Inn", 24), "a_stay_at_the_inn_level_24" },
        { ("Detour", 18), "detour_level_18" },
        { ("Detour", 24), "detour_level_24" },
        { ("Rest Stop", 18), "rest_stop_level_18" },
        { ("Rest Stop", 24), "rest_stop_level_24" },
        { ("Lost in the Swamp", 18), "lost_in_the_swamp_level_18" },
        { ("Lost in the Swamp", 24), "lost_in_the_swamp_level_24" },
        { ("The End of the Road", 18), "the_end_of_the_road_level_18" },
        { ("The End of the Road", 24), "the_end_of_the_road_level_24" },
        { ("Dream Conspiracy", 18), "dream_conspiracy" },
        { ("Finding the Path", 18), "finding_the_path" },
        { ("The Shipwrecked Spy", 18), "the_shipwrecked_spy" },
        { ("I Dream of Jeets", 18), "i_dream_of_jeets" },
        { ("The Mindsunder", 18), "the_mindsunder" },
        { ("Hound of Xoriat", 18), "hound_of_xoriat" },
        { ("A Vision of Destruction", 18), "a_vision_of_destruction" },
        { ("Enemy of My Enemy", 18), "enemy_of_my_enemy_level_18" },
        { ("Enemy of My Enemy", 34), "enemy_of_my_enemy_level_34" },
        { ("The Bark and the Blade", 18), "the_bark_and_the_blade_level_18" },
        { ("The Bark and the Blade", 34), "the_bark_and_the_blade_level_34" },
        { ("Paper Trail", 18), "paper_trail_level_18" },
        { ("Paper Trail", 34), "paper_trail_level_34" },
        { ("Party 101", 18), "party_101_level_18" },
        { ("Party 101", 34), "party_101_level_34" },
        { ("Taken in Hand", 18), "taken_in_hand_level_18" },
        { ("Taken in Hand", 34), "taken_in_hand_level_34" },
        { ("The Devils to Pay", 18), "the_devils_to_pay_level_18" },
        { ("The Devils to Pay", 34), "the_devils_to_pay_level_34" },
        { ("The Evil We Know", 18), "the_evil_we_know_level_18" },
        { ("The Evil We Know", 34), "the_evil_we_know_level_34" },
        { ("What Dreams May Come", 18), "what_dreams_may_come_level_18" },
        { ("What Dreams May Come", 34), "what_dreams_may_come_level_34" },
        { ("Grand Theft Aureon", 18), "grand_theft_aureon_level_18" },
        { ("Grand Theft Aureon", 34), "grand_theft_aureon_level_34" },
        { ("Vecna Denied", 18), "vecna_denied_level_18" },
        { ("Vecna Denied", 34), "vecna_denied_level_34" },
        { ("Vecna Unleashed (quest)", 18), "vecna_unleashed_quest_level_18" },
        { ("Vecna Unleashed (quest)", 34), "vecna_unleashed_quest_level_34" },
        { ("Turn the Page (quest)", 18), "turn_the_page_quest_level_18" },
        { ("Turn the Page (quest)", 34), "turn_the_page_quest_level_34" },
        { ("Law and Order", 18), "law_and_order_level_18" },
        { ("Law and Order", 34), "law_and_order_level_34" },
        { ("Murder by Night", 19), "murder_by_night" },
        { ("The Riddle", 19), "the_riddle" },
        { ("Blown to Bits", 19), "blown_to_bits" },
        { ("Power Play", 19), "power_play" },
        { ("Schemes of the Enemy", 19), "schemes_of_the_enemy" },
        { ("The Master Artificer", 19), "the_master_artificer" },
        { ("The Tracker's Trap", 19), "the_trackers_trap_level_19" },
        { ("The Tracker's Trap", 27), "the_trackers_trap_level_27" },
        { ("Lines of Supply", 19), "lines_of_supply_level_19" },
        { ("Lines of Supply", 27), "lines_of_supply_level_27" },
        { ("Breaking the Ranks", 19), "breaking_the_ranks_level_19" },
        { ("Breaking the Ranks", 27), "breaking_the_ranks_level_27" },
        { ("A Break In the Ice", 19), "a_break_in_the_ice_level_19" },
        { ("A Break In the Ice", 27), "a_break_in_the_ice_level_27" },
        { ("What Goes Up", 19), "what_goes_up_level_19" },
        { ("What Goes Up", 27), "what_goes_up_level_27" },
        { ("A New Invasion", 19), "a_new_invasion" },
        { ("Genesis Point", 19), "genesis_point" },
        { ("Bastion of Power", 19), "bastion_of_power" },
        { ("Wrath of the Flame", 19), "wrath_of_the_flame" },
        { ("The Weapons Shipment", 19), "the_weapons_shipment" },
        { ("Sins of Attrition", 19), "sins_of_attrition" },
        { ("Eye of the Titan", 19), "eye_of_the_titan" },
        { ("Reclaiming Memories", 19), "reclaiming_memories" },
        { ("Raiding the Giants' Vault", 19), "raiding_the_giants_vault" },
        { ("Mining for Ancient Secrets", 19), "mining_for_ancient_secrets" },
        { ("The Lord of Blades", 20), "the_lord_of_blades" },
        { ("Tower of Despair", 20), "tower_of_despair" },
        { ("The Dreaming Dark (quest)", 20), "the_dreaming_dark_quest" },
        { ("A Study in Sable", 26), "a_study_in_sable" },
        { ("Brothers of the Forge", 28), "brothers_of_the_forge" },
        { ("The Haunted Halls of Eveningstar", 28), "the_haunted_halls_of_eveningstar" },
        { ("Impossible Demands", 21), "impossible_demands" },
        { ("The Lost Thread", 21), "the_lost_thread" },
        { ("The Battle for Eveningstar", 21), "the_battle_for_eveningstar" },
        { ("The Unquiet Graves", 21), "the_unquiet_graves" },
        { ("Don't Drink the Water", 22), "dont_drink_the_water" },
        { ("The House of Broken Chains", 22), "the_house_of_broken_chains" },
        { ("The House of Rusted Blades", 22), "the_house_of_rusted_blades" },
        { ("The Portal Opens", 22), "the_portal_opens" },
        { ("In the Belly of the Beast", 22), "in_the_belly_of_the_beast" },
        { ("The House of Death Undone", 22), "the_house_of_death_undone" },
        { ("Trial by Fury", 23), "trial_by_fury" },
        { ("Reclaiming the Rift", 23), "reclaiming_the_rift" },
        { ("The Deal and the Demon", 23), "the_deal_and_the_demon" },
        { ("Caught in the Web", 24), "caught_in_the_web" },
        { ("Return to Cabal for One", 24), "return_to_cabal_for_one" },
        { ("Return to Madstone Crater", 24), "return_to_madstone_crater" },
        { ("Return to Prison of the Planes", 24), "return_to_prison_of_the_planes" },
        { ("Return to Gianthold Tor", 24), "return_to_gianthold_tor" },
        { ("The Fall of Truth", 25), "the_fall_of_truth" },
        { ("Inferno of the Damned (epic)", 29), "inferno_of_the_damned_epic" },
        { ("Desecrated Temple of Vol (epic)", 29), "desecrated_temple_of_vol_epic" },
        { ("Ghosts of Perdition (epic)", 29), "ghosts_of_perdition_epic" },
        { ("Flesh Maker's Laboratory (epic)", 29), "flesh_makers_laboratory_epic" },
        { ("Old Tomb, New Tenants", 25), "old_tomb_new_tenants" },
        { ("Precious Cargo", 25), "precious_cargo" },
        { ("A Legend Revisited", 25), "a_legend_revisited" },
        { ("Ghost of a Chance (epic)", 25), "ghost_of_a_chance_epic" },
        { ("Prove Your Worth (epic)", 25), "prove_your_worth_epic" },
        { ("The Chronoscope (Legendary)", 32), "the_chronoscope_legendary" },
        { ("Riding the Storm Out", 32), "riding_the_storm_out" },
        { ("Killing Time", 32), "killing_time" },
        { ("The Dryad and the Demigod", 32), "the_dryad_and_the_demigod" },
        { ("Legendary Tempest's Spine", 32), "legendary_tempests_spine" },
        { ("Legendary Hound of Xoriat", 32), "legendary_hound_of_xoriat" },
        { ("Den of Vipers", 36), "den_of_vipers" },
        { ("Hunt or Be Hunted", 32), "hunt_or_be_hunted" },
        { ("Pilgrims' Peril", 34), "pilgrims_peril" },
        { ("Stolen Power", 34), "stolen_power" },
        { ("Horde of the Illithid Controller", 34), "horde_of_the_illithid_controller" },
        { ("Astral Ambush", 34), "astral_ambush" },
        { ("Threats Old and New", 35), "threats_old_and_new" },
        { ("Too Hot to Handle", 32), "too_hot_to_handle" },
        { ("Project Nemesis", 32), "project_nemesis" },
        { ("The Curse of Strahd", 32), "the_curse_of_strahd" },
        { ("Old Baba's Hut", 32), "old_babas_hut" },
        { ("Legendary Master Artificer", 32), "legendary_master_artificer" },
        { ("Legendary Lord of Blades", 32), "legendary_lord_of_blades" },
        { ("Fire on Thunder Peak", 30), "fire_on_thunder_peak" },
        { ("Temple of the Deathwyrm", 30), "temple_of_the_deathwyrm" },
        { ("Skeletons in the Closet", 34), "skeletons_in_the_closet" },
        { ("The Mark of Death", 30), "the_mark_of_death" },
        { ("The Codex and the Shroud", 32), "the_codex_and_the_shroud" },
        { ("Legendary Vision of Destruction", 32), "legendary_vision_of_destruction" },
        { ("Defiler of the Just", 30), "defiler_of_the_just" },
        { ("Fire Over Morgrave", 34), "fire_over_morgrave" },
        { ("Relentless", 36), "relentless" },
    };

    public static string? GetQuestId(string questName, int level)
    {
        if (_questIds.TryGetValue((questName, level), out var id))
            return id;
        return null;
    }

    public static int Count => _questIds.Count;
}
