namespace QuestTracker;

/// <summary>
/// Quest variant lookup - maps quest names to all their level variants
/// </summary>
public static class QuestVariantLookup
{
    // Quests with multiple level versions (heroic/epic/legendary)
    private static readonly Dictionary<string, int[]> _questVariants = new(StringComparer.OrdinalIgnoreCase)
    {
        { "The Bugbear Bandits", new[] { 1, 21 } },
        { "Treasure Hunt", new[] { 1, 21 } },
        { "Caged Beast", new[] { 1, 21 } },
        { "Obstructing the Orcs", new[] { 1, 21 } },
        { "The Hobgoblin Horde", new[] { 1, 21 } },
        { "Violent Delights", new[] { 1, 21 } },
        { "Watch Your Step", new[] { 1, 21 } },
        { "Total Chaos", new[] { 2, 22 } },
        { "Back to Basics", new[] { 3, 32 } },
        { "The Haunting of Saltmarsh", new[] { 3, 32 } },
        { "Under the Cover of Darkness", new[] { 3, 32 } },
        { "What Sleeps Below", new[] { 3, 32 } },
        { "Down You Go", new[] { 3, 32 } },
        { "Danger at Dunwater", new[] { 3, 32 } },
        { "The Final Enemy", new[] { 3, 32 } },
        { "Swim at Your Own Risk", new[] { 3, 32 } },
        { "The Hijacked Haul", new[] { 3, 32 } },
        { "Rest for the Night", new[] { 3, 32 } },
        { "Sleeping with the Fishes", new[] { 3, 35 } },
        { "Endgame: Marguerite", new[] { 3, 23 } },
        { "Setting the Wards: The Patriarchs' Crypt", new[] { 3, 23 } },
        { "The Friar's Niece", new[] { 3, 23 } },
        { "The Old Archives", new[] { 3, 23 } },
        { "The Crypt of Gerard Dryden", new[] { 3, 23 } },
        { "Return to the Sanctuary", new[] { 3, 23 } },
        { "Setting the Wards: The Lower Cathedral", new[] { 3, 23 } },
        { "The Home of Memory", new[] { 3, 32 } },
        { "Heart of the Problem", new[] { 3, 32 } },
        { "The Sacred Bounty", new[] { 3, 32 } },
        { "Housekeeping", new[] { 3, 32 } },
        { "Rosemary's Ballad", new[] { 3, 32 } },
        { "Catastrophe", new[] { 4, 34 } },
        { "Rats in a Cage", new[] { 4, 34 } },
        { "The Wizard's Labyrinth", new[] { 4, 34 } },
        { "The Knife's Edge", new[] { 4, 34 } },
        { "The Darkness and the Light", new[] { 4, 35 } },
        { "The Covered Culvert", new[] { 4, 35 } },
        { "Endgame: The Archbishop's Fate", new[] { 4, 23 } },
        { "The Mystery of Delera's Tomb", new[] { 5, 27 } },
        { "The Endless Revels", new[] { 5, 32 } },
        { "The Legend of the Lost Locket", new[] { 5, 32 } },
        { "Make Believe", new[] { 5, 32 } },
        { "Wake Me Up Inside", new[] { 5, 32 } },
        { "Combatting Corruption", new[] { 5, 32 } },
        { "A Frosty Reception", new[] { 5, 32 } },
        { "Witch Hunt", new[] { 5, 32 } },
        { "A Small Problem", new[] { 5, 20 } },
        { "The Snitch", new[] { 5, 20 } },
        { "Under the Big Top", new[] { 5, 20 } },
        { "Partycrashers", new[] { 5, 20 } },
        { "Toil and Trouble", new[] { 5, 28 } },
        { "The Promise of Fire", new[] { 6, 27 } },
        { "Dread Sea Scrolls", new[] { 6, 32 } },
        { "Return to Delera's Tomb (quest)", new[] { 6, 27 } },
        { "The Chronoscope", new[] { 6, 21 } },
        { "Devil Assault (quest)", new[] { 6, 21 } },
        { "Quid Pro Quo", new[] { 6, 32 } },
        { "Needle in a Fey Stack", new[] { 6, 32 } },
        { "The Knight Who Cried Windmill", new[] { 6, 32 } },
        { "The Thornwright", new[] { 6, 32 } },
        { "Immortality Lessons", new[] { 6, 32 } },
        { "The Icemount Curse", new[] { 6, 32 } },
        { "Another Man's Treasure", new[] { 6, 21 } },
        { "Kind of a Big Deal", new[] { 6, 21 } },
        { "The Price of Freedom", new[] { 6, 25 } },
        { "Memory Lapse", new[] { 6, 23 } },
        { "The Missing Party", new[] { 7, 27 } },
        { "Free Delera", new[] { 7, 27 } },
        { "One Dame Thing After Another", new[] { 7, 32 } },
        { "Through the Tulgey Wood", new[] { 7, 32 } },
        { "Storm the Beaches", new[] { 7, 20 } },
        { "Bargain of Blood", new[] { 7, 20 } },
        { "The Tide Turns", new[] { 7, 20 } },
        { "The Black Loch", new[] { 7, 20 } },
        { "Captive of the Hidden God", new[] { 7, 33 } },
        { "The Curse and the Captive Crustacean", new[] { 7, 33 } },
        { "Bullywugs and Booby Traps", new[] { 7, 33 } },
        { "Plundering Pirates' Point", new[] { 7, 33 } },
        { "Spiders and Flies", new[] { 7, 33 } },
        { "The Stone Crypt Chronicle", new[] { 7, 33 } },
        { "The Trouble with Tar Pits", new[] { 7, 33 } },
        { "Trials of the Triceratops", new[] { 7, 33 } },
        { "Whispers of Return", new[] { 7, 33 } },
        { "Wild Thing", new[] { 7, 33 } },
        { "All Hail the King", new[] { 7, 33 } },
        { "Slave Pits of the Undercity", new[] { 8, 31 } },
        { "Secret of the Slavers' Stockade", new[] { 8, 31 } },
        { "Assault on the Aerie of the Slave Lords", new[] { 8, 31 } },
        { "Thrall of the Necromancer", new[] { 8, 27 } },
        { "Spies in the House", new[] { 8, 21 } },
        { "The Body Snatchers", new[] { 8, 36 } },
        { "The Proper Authorities", new[] { 8, 36 } },
        { "Ends and Means", new[] { 8, 36 } },
        { "A Light in the Attic", new[] { 8, 36 } },
        { "Cold Snap", new[] { 8, 36 } },
        { "Beneath the City Streets", new[] { 8, 36 } },
        { "Locked Away (Part One)", new[] { 8, 36 } },
        { "Snowfall and Sunlight", new[] { 8, 36 } },
        { "Locked Away (Part Two)", new[] { 8, 36 } },
        { "A Miner Sacrifice", new[] { 8, 36 } },
        { "The Wish", new[] { 8, 36 } },
        { "Special Delivery", new[] { 8, 36 } },
        { "Zoo Creeper", new[] { 8, 36 } },
        { "Body and Mind", new[] { 8, 36 } },
        { "Fall of the Forbidden Temple", new[] { 8, 34 } },
        { "ToEE: First Level and Earth Temple", new[] { 8, 34 } },
        { "ToEE: Water Node", new[] { 8, 34 } },
        { "ToEE: Lower Temple Complex", new[] { 8, 34 } },
        { "ToEE: Fire Node", new[] { 8, 34 } },
        { "ToEE: Earth Node", new[] { 8, 34 } },
        { "ToEE: Depths of the Temple", new[] { 8, 34 } },
        { "ToEE: Air Node", new[] { 8, 34 } },
        { "The Prisoner", new[] { 8, 21 } },
        { "Tharashk Arena", new[] { 8, 21 } },
        { "The Claw of Vulkoor", new[] { 9, 21 } },
        { "Fathom the Depths", new[] { 9, 21 } },
        { "Into the Deep", new[] { 9, 21 } },
        { "The Last Stand", new[] { 9, 21 } },
        { "Haywire Foundry", new[] { 9, 22 } },
        { "The Jungle of Khyber", new[] { 9, 22 } },
        { "White Plume Mountain", new[] { 9, 32 } },
        { "The Newcomers", new[] { 10, 31 } },
        { "Black and Blue", new[] { 10, 31 } },
        { "Into the Mists", new[] { 10, 31 } },
        { "Fresh-baked Dreams", new[] { 10, 31 } },
        { "Death House", new[] { 10, 31 } },
        { "An Invitation to Dinner", new[] { 10, 32 } },
        { "The Vault of Night", new[] { 10, 22 } },
        { "Plane of Night", new[] { 10, 22 } },
        { "An Offering of Blood", new[] { 11, 21 } },
        { "Oath of Vengeance", new[] { 11, 31 } },
        { "A Raven at the Door", new[] { 11, 31 } },
        { "Mad Tea Party", new[] { 11, 31 } },
        { "Sealed in Amber", new[] { 11, 31 } },
        { "Diplomatic Impunity", new[] { 12, 34 } },
        { "Eyes of Stone", new[] { 12, 34 } },
        { "Frame Work", new[] { 12, 34 } },
        { "Against the Demon Queen (quest)", new[] { 12, 22 } },
        { "The Chamber of Raiyum", new[] { 12, 22 } },
        { "Chains of Flame", new[] { 12, 22 } },
        { "Zawabi's Revenge", new[] { 12, 22 } },
        { "Wrath of the Earth", new[] { 12, 32 } },
        { "Sunrise", new[] { 12, 31 } },
        { "The Final Vintage", new[] { 12, 31 } },
        { "Ravens' Bane", new[] { 12, 31 } },
        { "An Element of Chaos", new[] { 12, 32 } },
        { "Eye Know Whodunnit", new[] { 12, 32 } },
        { "Seizing the Dawn", new[] { 12, 32 } },
        { "Beautiful Nightmares", new[] { 12, 32 } },
        { "Dinosaur Crisis", new[] { 13, 28 } },
        { "Blockade Buster", new[] { 13, 34 } },
        { "Undermine", new[] { 13, 34 } },
        { "Assault on Summerfield", new[] { 13, 34 } },
        { "Siegebreaker", new[] { 13, 34 } },
        { "Ettercap Incursion", new[] { 13, 35 } },
        { "Seeds of Decay", new[] { 13, 35 } },
        { "The Safehold", new[] { 13, 35 } },
        { "Death Hosts This Banquet", new[] { 13, 35 } },
        { "Oghma's Song", new[] { 13, 35 } },
        { "Secrets of the Red Wizards", new[] { 13, 35 } },
        { "Portal to Below", new[] { 13, 35 } },
        { "Book Burning", new[] { 13, 35 } },
        { "Times Long Past", new[] { 13, 35 } },
        { "The Key to the Mythal", new[] { 13, 35 } },
        { "The Zulkir's Plan", new[] { 13, 35 } },
        { "Voices of the Dead", new[] { 13, 35 } },
        { "The House of Gems", new[] { 13, 35 } },
        { "A Cry for Help", new[] { 13, 24 } },
        { "Feast or Famine", new[] { 13, 24 } },
        { "Foundation of Discord", new[] { 13, 24 } },
        { "The Maze of Madness", new[] { 13, 24 } },
        { "Trial by Fire", new[] { 13, 24 } },
        { "The Archons' Trial", new[] { 13, 30 } },
        { "Demon Assault", new[] { 13, 30 } },
        { "The Devil's Details", new[] { 13, 30 } },
        { "Tower of Frost", new[] { 14, 28 } },
        { "Night Falls on Stormreach", new[] { 14, 31 } },
        { "Quarantine", new[] { 14, 31 } },
        { "The Madness of Crowds", new[] { 14, 31 } },
        { "Toxic Treatment", new[] { 14, 31 } },
        { "The Age of Rage", new[] { 14, 31 } },
        { "The Crucible", new[] { 14, 24 } },
        { "Tavern Brawl", new[] { 14, 30 } },
        { "Grim and Barett", new[] { 14, 30 } },
        { "Subversion", new[] { 14, 30 } },
        { "Multitude of Menace", new[] { 14, 30 } },
        { "Search and Rescue", new[] { 15, 31 } },
        { "Lost at Sea", new[] { 15, 32 } },
        { "Just Business", new[] { 15, 32 } },
        { "Ruinous Schemes", new[] { 15, 32 } },
        { "Smash and Burn", new[] { 15, 32 } },
        { "A Sharn Welcome", new[] { 15, 32 } },
        { "Best Laid Plans", new[] { 15, 32 } },
        { "Red Rain", new[] { 15, 32 } },
        { "The Wraithcallers", new[] { 15, 32 } },
        { "Thralls of the Fungus Lord", new[] { 15, 32 } },
        { "The Same Old Song", new[] { 15, 32 } },
        { "Graveyard Shift", new[] { 15, 31 } },
        { "Records of the Past", new[] { 15, 31 } },
        { "Third Time's a Charm", new[] { 15, 31 } },
        { "Strike Back", new[] { 15, 31 } },
        { "Desire in the Dark", new[] { 15, 31 } },
        { "To Curse the Sky", new[] { 15, 31 } },
        { "Creeping Death", new[] { 15, 31 } },
        { "The Lords of Dust", new[] { 16, 21 } },
        { "The Spinner of Shadows", new[] { 16, 21 } },
        { "Servants of the Overlord", new[] { 16, 21 } },
        { "The Mask of Deception", new[] { 16, 30 } },
        { "Beyond the Rift", new[] { 16, 21 } },
        { "Army of Eternal Night", new[] { 16, 33 } },
        { "Order in the Court!", new[] { 16, 33 } },
        { "Growing Pains", new[] { 16, 33 } },
        { "The Hand and the Eyes", new[] { 16, 33 } },
        { "Three Paths to Battle", new[] { 16, 33 } },
        { "No Refunds", new[] { 16, 32 } },
        { "House of Pain", new[] { 16, 32 } },
        { "Blown Deadline", new[] { 16, 32 } },
        { "Reach for the Sky", new[] { 16, 32 } },
        { "Scavenger Hunt", new[] { 16, 32 } },
        { "The Magma Must Flow", new[] { 16, 32 } },
        { "Security Detail", new[] { 16, 32 } },
        { "Roll Call", new[] { 16, 32 } },
        { "A Lesson in Deception", new[] { 16, 26 } },
        { "Army of Shadow", new[] { 16, 26 } },
        { "Friends in Low Places", new[] { 16, 26 } },
        { "The Thrill of the Hunt", new[] { 16, 26 } },
        { "Through a Mirror Darkly", new[] { 16, 26 } },
        { "Good Intentions", new[] { 17, 31 } },
        { "Outbreak", new[] { 17, 23 } },
        { "Thorn and Paw", new[] { 17, 23 } },
        { "Overgrowth", new[] { 17, 23 } },
        { "The Druid's Curse", new[] { 17, 23 } },
        { "Safety in Numbers", new[] { 17, 32 } },
        { "Finding Dorris", new[] { 17, 32 } },
        { "The Underlane Assignment", new[] { 17, 32 } },
        { "Members Only", new[] { 17, 32 } },
        { "The Offshore Account", new[] { 17, 32 } },
        { "Soul Survivor", new[] { 17, 32 } },
        { "Kill Ten Rats", new[] { 18, 34 } },
        { "Fashion Madness", new[] { 18, 26 } },
        { "Terminal Delirium", new[] { 18, 26 } },
        { "Palace of Stone", new[] { 18, 26 } },
        { "Fred's First Date", new[] { 18, 34 } },
        { "This Old Haunt", new[] { 18, 34 } },
        { "Too Many Cooks", new[] { 18, 34 } },
        { "A Stay at the Inn", new[] { 18, 24 } },
        { "Detour", new[] { 18, 24 } },
        { "Rest Stop", new[] { 18, 24 } },
        { "Lost in the Swamp", new[] { 18, 24 } },
        { "The End of the Road", new[] { 18, 24 } },
        { "Enemy of My Enemy", new[] { 18, 34 } },
        { "The Bark and the Blade", new[] { 18, 34 } },
        { "Paper Trail", new[] { 18, 34 } },
        { "Party 101", new[] { 18, 34 } },
        { "Taken in Hand", new[] { 18, 34 } },
        { "The Devils to Pay", new[] { 18, 34 } },
        { "The Evil We Know", new[] { 18, 34 } },
        { "What Dreams May Come", new[] { 18, 34 } },
        { "Grand Theft Aureon", new[] { 18, 34 } },
        { "Vecna Denied", new[] { 18, 34 } },
        { "Vecna Unleashed (quest)", new[] { 18, 34 } },
        { "Turn the Page (quest)", new[] { 18, 34 } },
        { "Law and Order", new[] { 18, 34 } },
        { "The Tracker's Trap", new[] { 19, 27 } },
        { "Lines of Supply", new[] { 19, 27 } },
        { "Breaking the Ranks", new[] { 19, 27 } },
        { "A Break In the Ice", new[] { 19, 27 } },
        { "What Goes Up", new[] { 19, 27 } },
    };

    public static int[]? GetVariantLevels(string questName)
    {
        if (_questVariants.TryGetValue(questName, out var levels))
            return levels;
        return null;
    }

    public static bool HasVariants(string questName) => _questVariants.ContainsKey(questName);
}
